#pragma once

#include <vector>
#include <iostream>

#define MIN_OPT 0
#define MAX_OPT 107 

#define NONE 0
#define BASICAA 1
#define EARLY_CSE 2
#define _GVN 3
#define INSTCOMBINE 4
#define INDVARS 5
#define LICM 6
#define LOOP_INSTSIMPLIFY 7
#define LOOP_REDUCE 8
#define LOOP_IDIOM 9
#define LOOP_DELETION 10
#define LOOP_ROTATE 11
#define LOOP_UNROLL 12
#define REASSOCIATE 13
#define SIMPLIFYCFG 14
#define TAILCALLELIM 15
#define UNROLL_ALLOW_PARTIAL 16
#define SIMPLIFY_LIBCALLS 17
#define SCALARREPL 18
#define CONSTPROP 19 
#define ALIGNMENT_FROM_ASSSUMPTIONS 20
#define SCCP 21
#define DCE 22
#define DIE 23
#define DSE 24
#define CALLSITE_SPLITTING 25
#define ADCE 26
#define GUARD_WIDENING 27
#define BDCE 28
#define IRCE 29
#define LOOP_SINK 30
#define LOOP_PREDICATION 31
#define SCALARIZER 32
#define LOOP_UNSWITCH 33
#define LOOP_UNROLL_AND_JAM 34
#define LOOP_REROLL 35
#define LOOP_VERSIONING_LICM 36
#define JUMP_THREADING 37
#define FLATTENCFG 38
#define STRUCTURIZECFG 39
#define _GVN_HOIST 40
#define _GVN_SINK 41
#define MLDST_MOTION 42
#define NEWGVN 43
#define MEMCPYOPT 44 
#define CONSTHOIST 45
#define SINK 46
#define LOWERATOMIC 47
#define LOWER_GUARD_INTRINSIC 48
#define MERGEICMPS 49
#define CORRELATED_PROPAGATION 50
#define LOWER_EXPECT 51
#define PARTIALLY_INLINE_LIBCALLS 52
#define SEPARATE_CONST_OFFSET_FROM_GEP 53
#define SLSR 54
#define PLACE_SAFEPOINTS 55
#define FLOAT2INT 56
#define NARY_REASSOCIATE 57
#define LOOP_DISTRIBUTE 58
#define LOOP_LEAD_ELIM 59
#define LOOP_VERSIONING 60
#define LOOP_DATA_PREFETCH 61
#define INSTSIMPLIFY 62
#define AGGRESSIVE_INSTCOMBINE 63
#define LOWERINVOKE 64
#define INSTNAMER 65
#define LOWERSWITCH 66
#define BREAK_CRIT_EDGES 67
#define LCSSA 68
#define MEM2REG 69
#define LOOP_SINMPLIFY 70
#define LOOP_VECTORIZE 71
#define SLP_VECTORIZER 72
#define LOAD_STORE_VECTORIZER 73
#define LAZY_VALUE_INFO 74
#define DA 75
#define COST_MODEL 76
#define DELINEARIZE 77
#define DIVERGENCE 78
#define INSTCOUNT 79
#define REGIONS 80
#define DOMTREE 81
#define CONSTMERGE 82
#define GLOBALOPT 83
#define INLINE 84
#define IPSCCP 85
#define PARTIAL_INLINER 86
#define REWRITE_STATEPOINTS_FOR_GCC 87
#define STRIP 88
#define STRIP_NONDEBUG 89
#define STRIP_DEBUG_DECLARE 90
#define STRIP_DEAD_DEBUG_INFO 91
#define	GLOBALDCE 92
#define ELIM_AVAIL_EXTERN 93
#define	PRUNE_EH 94
#define	DEADARGELIM 95
#define ARGPROMOTION 96
#define IPCONSTPROP 97
#define LOOP_EXTRACT 98
#define LOOP_EXTRACT_SINGLE 99
#define EXTRACT_BLOCKS 100
#define STRIP_DEAD_PROTOTYPES 101
#define MERGE_FUNC 102
#define BARRIER 103
#define CALLED_VALUE_PROPAGATION 104
#define CROSS_DSO_CFI 105
#define GLOBALSPLIT 106
#define METARENAMER 107
#define PA_EVAL 108
#define INTERNALIZE 109
#define INFER_ADDRESS_SPACES 110
#define SPECULATIVE_EXECUTION 111
#define CODEGENPREPARE 112
#define LOOP_GUARD_WIDENING 113
#define DIV_REM_PAIRS 114
#define LOOP_INTERCHANGE 115 
#define SROA 116

static std::vector<std::vector<uint16_t>> BEST10_SET = {
  {INSTCOMBINE, SIMPLIFYCFG, _GVN, INDVARS, LOOP_ROTATE, UNROLL_ALLOW_PARTIAL, LOOP_UNROLL, 
    LOOP_ROTATE, LOOP_UNROLL, _GVN, INLINE, EARLY_CSE, BASICAA, REASSOCIATE, INSTCOMBINE},
  {SIMPLIFY_LIBCALLS, SIMPLIFYCFG, UNROLL_ALLOW_PARTIAL, INTERNALIZE, _GVN, INSTCOMBINE, INLINE, 
    GLOBALOPT, SCALARREPL, LOOP_ROTATE, LOOP_UNROLL, LOOP_INSTSIMPLIFY},
  {_GVN, LOOP_ROTATE, INTERNALIZE, INLINE, LICM, TAILCALLELIM, INSTCOMBINE, BASICAA, INDVARS},
  {CODEGENPREPARE, LOOP_ROTATE, LOOP_IDIOM, LOOP_DELETION, _GVN},
  {LOOP_ROTATE, INLINE, SIMPLIFY_LIBCALLS, BASICAA, LICM, CONSTMERGE, INDVARS, UNROLL_ALLOW_PARTIAL, 
    LOOP_UNROLL, REASSOCIATE, _GVN},
  {SIMPLIFYCFG, TAILCALLELIM, EARLY_CSE, LOOP_ROTATE, INTERNALIZE, PARTIAL_INLINER, INSTCOMBINE, 
    INLINE, IPSCCP},
  {INTERNALIZE, INLINE, GLOBALOPT, EARLY_CSE, LICM, BASICAA, INDVARS, LOOP_REDUCE},
  {CODEGENPREPARE, _GVN, TAILCALLELIM, REASSOCIATE, BASICAA, INLINE, LOOP_ROTATE, INDVARS, 
    REASSOCIATE},
  {SIMPLIFYCFG, TAILCALLELIM, INSTCOMBINE, EARLY_CSE},
  {EARLY_CSE, SIMPLIFYCFG, _GVN, INLINE, LOOP_REDUCE, LICM, INSTCOMBINE, _GVN, REASSOCIATE}
};
